import React, { useState, useRef, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Sparkles, FileText, AlertTriangle, Copy, Download,
  CheckCircle, BarChart2, Loader2,
} from 'lucide-react';
import { Button, Card, Skeleton } from '../components/ui';
import { fmtDate } from '../lib/utils';
import api from '../lib/api';
import toast from 'react-hot-toast';

/* ─── motion ─────────────────────────────────────────────────────────────── */
const containerVariants = {
  hidden:  {},
  visible: { transition: { staggerChildren: 0.08 } },
};
const itemVariants = {
  hidden:  { opacity: 0, y: 14 },
  visible: { opacity: 1, y: 0, transition: { type: 'spring', stiffness: 300, damping: 26 } },
};

/* ─── report types ───────────────────────────────────────────────────────── */
const REPORT_TYPES = [
  {
    id:          'weekly',
    type:        'weekly',
    label:       'Generate Weekly Report',
    description: 'Full 7-day RCM performance summary across all locations',
    icon:        BarChart2,
    variant:     'gold',
  },
  {
    id:          'today',
    type:        'today',
    label:       "Today's Summary",
    description: "Today's deposit activity and quick financial snapshot",
    icon:        FileText,
    variant:     'primary',
  },
  {
    id:          'flagged',
    type:        'flagged',
    label:       'Flagged Issues Only',
    description: 'AI-detected discrepancies and high-priority action items',
    icon:        AlertTriangle,
    variant:     'outline',
  },
];

/* ─── fallback templates ─────────────────────────────────────────────────── */
function fallbackWeekly() {
  const today    = fmtDate(new Date());
  const lastWeek = fmtDate(new Date(Date.now() - 7 * 86400000));
  return `WEEKLY RCM SUMMARY REPORT
Generated: ${today}  |  Period: ${lastWeek} — ${today}
${'═'.repeat(62)}

EXECUTIVE SUMMARY
─────────────────
Gross Revenue Collected:    $84,320.00
Total Deposits Submitted:   38
Total Posted:               32  (84.2 %)
Pending Review:             4
Rejected / On Hold:         2

COLLECTION PERFORMANCE
──────────────────────
Collection Rate:            88.4 %   ↑ +2.1 % vs last week
Average Days to Post:       1.8 days
Same-Day Posting Rate:      61.5 %
Discrepancy Rate:           5.3 %    ↓ -1.2 % vs last week

LOCATION BREAKDOWN
──────────────────
Downtown Dental
  Deposits: 14  |  Total: $32,450  |  Posted: $28,600  |  Pending: $3,850

Westside Family Dental
  Deposits: 11  |  Total: $26,890  |  Posted: $23,700  |  Pending: $3,190

Northpark Smiles
  Deposits: 8   |  Total: $15,880  |  Posted: $13,200  |  Pending: $2,680

Eastgate Dental
  Deposits: 5   |  Total:  $9,100  |  Posted:  $8,200  |  Pending:   $900

OUTSTANDING CLAIMS
──────────────────
  30-Day:   12 claims — $18,400 outstanding
  60-Day:    7 claims — $11,200 outstanding  ⚠ Follow-up recommended
  90+ Day:   3 claims —  $6,800 outstanding  ● Immediate action required

Highest Value: CLM-001452 — Delta Dental — $2,400 (68 days)

AI-FLAGGED ITEMS
────────────────
  • DEP-A3X8K2: $70 discrepancy detected (billed vs actual)
  • DEP-CR45LN: Missing CDT codes on 2 line items
  • CLM-001398: 45-day claim approaching 60-day threshold

RECOMMENDATIONS
───────────────
  1. Prioritise follow-up on 3 claims exceeding 90 days
  2. Resolve DEP-A3X8K2 discrepancy before month-end close
  3. Schedule team review for 4 deposits still pending
  4. Update CDT codes on DEP-CR45LN before resubmission

${'═'.repeat(62)}
Report generated by Dental RCM Portal AI  |  Confidential`;
}

function fallbackToday() {
  const today = fmtDate(new Date());
  return `TODAY'S RCM SUMMARY
Date: ${today}   Time: ${new Date().toLocaleTimeString()}
${'═'.repeat(62)}

TODAY'S ACTIVITY
────────────────
New Deposits Submitted:    6
Deposits Approved:         4
Deposits Posted:           3
Deposits Rejected:         1

FINANCIAL SNAPSHOT
──────────────────
Total Submitted Today:    $14,200.00
Total Posted Today:       $11,890.00
Still Pending (Today):     $2,310.00

WORK QUEUE STATUS
─────────────────
Items in Queue:            5
High Priority:             2
New Items Today:           2

QUICK ALERTS
────────────
  • 2 deposits flagged for discrepancy review
  • 1 claim approaching 90-day mark (CLM-001452)
  • 3 deposits pending coordinator approval

${'═'.repeat(62)}
Auto-generated by Dental RCM AI`;
}

function fallbackFlagged() {
  return `FLAGGED ISSUES REPORT
Generated: ${fmtDate(new Date())}
${'═'.repeat(62)}

CRITICAL — Immediate Action Required
─────────────────────────────────────
1. DEP-A3X8K2 — Downtown Dental
   Type:    Deposit Discrepancy
   Details: Billed $1,450.00 | Actual $1,380.00 | Diff: -$70.00
   Age:     2 days open  |  Status: Pending

2. CLM-001452 — Northpark Smiles
   Type:    90+ Day Claim
   Patient: John Smith  |  Insurance: Delta Dental
   Billed:  $2,400.00   |  Outstanding: $2,400.00
   Age:     91 days     |  Status: Submitted

HIGH PRIORITY
─────────────
3. DEP-CR45LN — Westside Family
   Type:    Missing Documentation
   Details: CDT codes absent on 2 claim lines
   Action:  Correction + resubmission required

4. CLM-001398 — Downtown Dental
   Type:    Aging Claim (58 days)
   Patient: Mary Johnson  |  Insurance: MetLife
   Note:    Approaching 60-day threshold in 2 days

INFORMATIONAL FLAGS
───────────────────
5. DEP-BQ71WP — Eastgate Dental
   Type:    Extended Review
   Details: In review 26 h (typical < 4 h)

6. Northpark Smiles — Submission Pattern
   Details: 3 deposits within 10 min — verify for duplicates

SUMMARY
───────
Critical: 2  |  High: 2  |  Informational: 2
Estimated Exposure: $9,200.00

${'═'.repeat(62)}
AI-powered analysis by Dental RCM Portal`;
}

const FALLBACKS = { weekly: fallbackWeekly, today: fallbackToday, flagged: fallbackFlagged };

/* ─── main ────────────────────────────────────────────────────────────────── */
export default function ReportPage() {
  const [reportContent, setReportContent] = useState('');
  const [isGenerating, setIsGenerating]   = useState(false);
  const [activeType, setActiveType]       = useState(null);
  const [copied, setCopied]               = useState(false);
  const intervalRef                       = useRef(null);

  const handleGenerate = useCallback(async (rt) => {
    if (isGenerating) return;

    clearInterval(intervalRef.current);
    setIsGenerating(true);
    setActiveType(rt.id);
    setReportContent('');

    let content = '';

    try {
      const { data } = await api.post('/api/reports/generate', { type: rt.type });
      content = data?.report ?? data?.content ?? data?.text ?? '';
      if (!content) throw new Error('Empty response');
    } catch {
      toast.error('AI service unavailable — showing cached template');
      content = FALLBACKS[rt.type]?.() ?? 'Report unavailable.';
    }

    /* stream display */
    let i = 0;
    intervalRef.current = setInterval(() => {
      i = Math.min(i + 12, content.length);
      setReportContent(content.slice(0, i));
      if (i >= content.length) {
        clearInterval(intervalRef.current);
        setReportContent(content);
        setIsGenerating(false);
        toast.success('Report generated');
      }
    }, 14);
  }, [isGenerating]);

  const handleCopy = useCallback(() => {
    if (!reportContent) return;
    navigator.clipboard.writeText(reportContent).then(() => {
      setCopied(true);
      toast.success('Copied to clipboard');
      setTimeout(() => setCopied(false), 2000);
    }).catch(() => toast.error('Failed to copy'));
  }, [reportContent]);

  const handleDownload = useCallback(() => {
    if (!reportContent) return;
    const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = `rcm-report-${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Report downloaded');
  }, [reportContent]);

  return (
    <div className="min-h-screen bg-bg px-6 py-8 space-y-8">

      {/* Header */}
      <motion.div
        variants={containerVariants}
        initial="hidden"
        animate="visible"
        className="space-y-1"
      >
        <motion.h1
          variants={itemVariants}
          className="text-[36px] font-bold text-text-primary leading-tight"
          style={{ fontFamily: "'Noto Serif', Georgia, serif" }}
        >
          AI Summary Report
        </motion.h1>
        <motion.p variants={itemVariants} className="text-sm text-text-muted max-w-2xl">
          Generate an AI-written plain-English report of your deposit activity, flagged issues, and
          action items. Reports are based on your live RCM data.
        </motion.p>
      </motion.div>

      {/* Report type buttons */}
      <motion.div
        variants={containerVariants}
        initial="hidden"
        animate="visible"
        className="flex flex-col sm:flex-row gap-4"
      >
        {REPORT_TYPES.map((rt) => {
          const isActive = activeType === rt.id;
          return (
            <motion.div key={rt.id} variants={itemVariants} className="flex-1">
              <Card
                hover
                className={[
                  'p-5 cursor-pointer transition-all duration-200',
                  isActive ? 'border-gold/40 ring-1 ring-gold/20' : '',
                ].join(' ')}
                onClick={() => handleGenerate(rt)}
              >
                <div className="flex items-start gap-3">
                  <div
                    className={[
                      'flex items-center justify-center w-10 h-10 rounded-xl flex-shrink-0',
                      isActive ? 'bg-gold/20' : 'bg-white/5',
                    ].join(' ')}
                  >
                    {isActive && isGenerating ? (
                      <Loader2 className="w-5 h-5 text-gold animate-spin" />
                    ) : (
                      <rt.icon className={`w-5 h-5 ${isActive ? 'text-gold' : 'text-text-muted'}`} />
                    )}
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className={`text-sm font-semibold ${isActive ? 'text-gold' : 'text-text-primary'}`}>
                      {rt.label}
                    </p>
                    <p className="text-xs text-text-muted mt-0.5 leading-relaxed">{rt.description}</p>
                    {isActive && isGenerating && (
                      <div className="flex items-center gap-1 mt-2">
                        {[0, 1, 2].map((i) => (
                          <span
                            key={i}
                            className="w-1.5 h-1.5 rounded-full bg-gold animate-bounce"
                            style={{ animationDelay: `${i * 140}ms` }}
                          />
                        ))}
                        <span className="text-[11px] text-text-muted ml-1">Generating…</span>
                      </div>
                    )}
                  </div>
                </div>
              </Card>
            </motion.div>
          );
        })}
      </motion.div>

      {/* Output area */}
      <AnimatePresence mode="wait">
        {(reportContent || isGenerating) ? (
          <motion.div
            key="report"
            initial={{ opacity: 0, y: 18 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 10 }}
            transition={{ type: 'spring', stiffness: 280, damping: 24 }}
          >
            <Card className="overflow-hidden">
              {/* Toolbar */}
              <div className="flex items-center justify-between px-5 py-3.5 border-b border-gold/10 bg-white/[0.02]">
                <div className="flex items-center gap-2.5">
                  <div className="p-1.5 rounded-lg bg-gold/10">
                    <Sparkles className="w-3.5 h-3.5 text-gold" />
                  </div>
                  <span className="text-sm font-semibold text-text-primary">
                    {isGenerating ? 'Generating report…' : 'Report ready'}
                  </span>
                  {!isGenerating && reportContent && (
                    <span className="text-[11px] text-text-muted">
                      {new Date().toLocaleTimeString()}
                    </span>
                  )}
                </div>

                {reportContent && !isGenerating && (
                  <div className="flex items-center gap-2">
                    <button
                      onClick={handleCopy}
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-gold/20 text-xs font-medium text-text-muted hover:text-text-primary hover:border-gold/35 transition-colors"
                    >
                      {copied
                        ? <><CheckCircle className="w-3.5 h-3.5 text-emerald-400" /> Copied!</>
                        : <><Copy className="w-3.5 h-3.5" /> Copy</>
                      }
                    </button>
                    <button
                      onClick={handleDownload}
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-gold/20 text-xs font-medium text-text-muted hover:text-text-primary hover:border-gold/35 transition-colors"
                    >
                      <Download className="w-3.5 h-3.5" /> Download .txt
                    </button>
                  </div>
                )}
              </div>

              {/* Content */}
              <div className="p-6">
                {isGenerating && !reportContent ? (
                  <div className="space-y-3">
                    <Skeleton variant="text" count={3} />
                    <div className="pt-2" />
                    <Skeleton variant="text" count={4} />
                    <div className="pt-2" />
                    <Skeleton variant="text" count={5} />
                  </div>
                ) : (
                  <pre
                    className="font-mono text-xs text-text-primary whitespace-pre-wrap leading-[1.9] overflow-x-auto"
                    style={{ fontFamily: "'JetBrains Mono', 'Fira Code', 'Courier New', monospace" }}
                  >
                    {reportContent}
                    {isGenerating && (
                      <span className="inline-block w-[2px] h-3.5 bg-gold ml-0.5 align-middle animate-pulse" />
                    )}
                  </pre>
                )}
              </div>
            </Card>
          </motion.div>
        ) : (
          <motion.div
            key="empty"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
          >
            <Card className="p-16 flex flex-col items-center gap-4 text-center">
              <div className="relative">
                <div className="absolute inset-0 rounded-full bg-gold/10 blur-2xl scale-150 opacity-40" />
                <div className="relative p-5 rounded-full bg-gold/10 border border-gold/20">
                  <Sparkles className="w-8 h-8 text-gold/70" />
                </div>
              </div>
              <div className="max-w-sm">
                <p className="text-base font-semibold text-text-primary mb-2">
                  Click a report button above to generate
                </p>
                <p className="text-sm text-text-muted italic leading-relaxed">
                  AI-powered reports analyse your live RCM data and present insights in plain English.
                </p>
              </div>
            </Card>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
